name: CI

on:
  push:
    # Build on tags that look like releases
    tags:
      - v*
    # Build when main or testing is pushed to
    branches:
      - main

jobs:
  sphinx-docs:
    name: Check sphinx docs on Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Install Sphinx dependencies
      run: |
        cd docs
        pip install -r requirements.txt
        sphinx-build -b html . _build
    - if: github.repository == 'johnlouieabrina-acn/ctwrap'
      name: Commit documentation changes
      run: |
        git clone https://github.com/johnlouieabrina-acn/ctwrap.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - if: github.repository == 'johnlouieabrina-acn/ctwrap'
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
